#!/usr/bin/env bash
set -e
MAJOR=7
VERSION=${MAJOR}.0.42

dir=apache-tomcat-$VERSION
archive=$dir.tar.gz

mkdir -p upstream
pushd upstream
wget http://archive.apache.org/dist/tomcat/tomcat-${MAJOR}/v${VERSION}/bin/${archive}
tar zxvf $archive

pushd $dir
for p in $(find ../../patches/perf/ -name '*.patch' | sort); do
    echo "Applying $p"
    patch -p1 < $p
done
popd

popd


mkdir ROOTFS
mkdir -p ROOTFS/usr/tomcat
mv upstream/$dir/* ROOTFS/usr/tomcat
