#!/bin/sh -e

#
# Copyright (C) 2013 Cloudius Systems, Ltd.
#
# This work is open source software, licensed under the terms of the
# BSD license as described in the LICENSE file in the top-level directory.
#

rm -rf upstream install

dir=http://mirrors.kernel.org/fedora/development/rawhide/x86_64/os/Packages/j/
basename=java-1.8.0-openjdk-headless-
suffix=.x86_64.rpm

fullname=$(wget -O- "${dir}"  \
          | grep -Eo "${basename}[a-zA-Z0-9\.-]+${suffix}" \
          | head -n 1)

mkdir  upstream
mkdir  install

wget -O upstream/jdk8.rpm "${dir}${fullname}"

# also get tzdata-java package, which Fedora Java 8 package needs
dir=http://mirrors.kernel.org/fedora/development/rawhide/x86_64/os/Packages/t/
basename=tzdata-java
suffix=.noarch.rpm
fullname=$(wget -O- "${dir}"  \
          | grep -Eo "${basename}[a-zA-Z0-9\.-]+${suffix}" \
          | head -n 1)
wget -O upstream/tzdata-java.rpm "${dir}${fullname}"
