#!/bin/sh
set -e
VERSION=3.0.5
SRC_DIR=kv-ce-$VERSION
TARBALL=$SRC_DIR.tar.gz
if [ ! -e $TARBALL ];then
    wget -c http://download.oracle.com/otn-pub/otn_software/nosql-database/$TARBALL
fi
rm -rf $SRC_DIR
tar zxf $TARBALL
