#!/bin/sh
VERSION=1.7.16.1
wget http://jruby.org.s3.amazonaws.com/downloads/$VERSION/jruby-complete-$VERSION.jar
mv jruby-complete-$VERSION.jar jruby-complete.jar
mkdir gemjar
java -jar jruby-complete.jar -S gem install -i ./gemjar sinatra --no-rdoc --no-ri
jar cf jruby-extensions.jar -C ./gemjar .
rm -rf gemjar
