#!/bin/sh

wget https://dbstudy.info/mysql/4.1.25/mysql-4.1.25.tar.gz
tar xf mysql-4.1.25.tar.gz

cp -a mysql-4.1.25 host
mv mysql-4.1.25 guest

cd host
./configure
make -j4
mkdir share bin data
cd share
ln -sf ../sql/share mysql
cd ../bin
ln -sf ../sql/mysqld .
ln -sf ../scripts/mysql_create_system_tables .
cd ..
./scripts/mysql_install_db --force --basedir=./ --ldata=data
cat <<EOF | eval './/bin/mysqld   --bootstrap --skip-grant-tables --basedir=./ --datadir=data --skip-innodb --skip-bdb --skip-ndbcluster  --max_allowed_packet=8M --net_buffer_length=16K'
use mysql;
set table_type=myisam;
insert into user values('%', 'admin', password('osv'), 'Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','','','','',0,0,0);
EOF

cd ../guest
./configure
patch -p1 < ../mysql-osv.diff
cp ../config.h .
cp ../host/sql/lex_hash.h sql/
cp -a ../host/sql/share/*/ sql/share/
make CXXFLAGS="-fPIC -DUSE_MUTEX_INSTEAD_OF_RW_LOCKS" CFLAGS="-fPIC -DUSE_MUTEX_INSTEAD_OF_RW_LOCKS" LDFLAGS="-shared" -j4

cd  ../
mkdir -p ROOTFS/etc
cp my.cnf ROOTFS/etc
mkdir -p ROOTFS/mysql41/
cp -a host/data ROOTFS/mysql41/
mkdir -p ROOTFS/usr/local/share/mysql
cp -a host/sql/share/*/ ROOTFS/usr/local/share/mysql
cp guest/sql/mysqld ROOTFS/mysql41/
