#!/bin/bash

set -e

cd "$(dirname "$0")"

if test $# -ne 1
then
  echo "usage: $0 <node-version>" 1>&2
  exit 1
fi

cd "node-$1"

ed -s node.gyp << EOF
,s/\(['"]\)executable\1/\1shared_library\1/
g/'-Wl,--whole-archive/d
g/'<(node_core_target_name)<(STATIC_LIB_SUFFIX)',/d
w
EOF

ed -s node.gypi << EOF
,g/'-Wl,--whole-archive/d
w
EOF


ed -s common.gypi << EOF
,s/'cflags':.*'-pthread'/&, '-fPIC'/
w
EOF

ed -s tools/gyp/pylib/gyp/generator/make.py << EOF
,s/-Wl,--whole-archive//g
w
EOF

#patch -p1 <../gcc7.patch
