#
# Copyright (C) 2016 Waldemar Kozaczuk
#
# This work is open source software, licensed under the terms of the
# BSD license as described in the LICENSE file in the top-level directory.
#

PROFILE_NUMBER=2
include ../openjdk8-zulu-compact-common/common.gmk

.PHONY: module clean
