#!/bin/sh

# Build a directory from the upstream redis 
set -e

VERSION=3.0.0-beta3
mkdir upstream
cd upstream
wget https://github.com/antirez/redis/archive/$VERSION.tar.gz
tar zxvf $VERSION.tar.gz
cd redis-$VERSION
# TODO: The top-level make's "-r" option breaks redis's inner makefiles.
# MAKEFLAGS should probably have been unset before calling us, not here.
unset MAKEFLAGS
make CFLAGS="-fPIC" LDFLAGS="-shared" MALLOC=libc
cp src/redis-server ../..
cd ../..
pwd
echo "/redis-server: ${PWD}/upstream/redis-$VERSION/src/redis-server" > usr.manifest
echo "/redis.conf: ${PWD}/redis.conf" >> usr.manifest
