#!/bin/sh

# Build a directory from the upstream redis 
set -e

VERSION=3.0.0-beta3
mkdir upstream
cd upstream
wget https://github.com/antirez/redis/archive/$VERSION.tar.gz
tar zxvf $VERSION.tar.gz
cd redis-$VERSION
make CFLAGS="-fPIC" LDFLAGS="-shared" MALLOC=libc
cd ../..
pwd
echo "/redis-server: ${PWD}/upstream/redis-$VERSION/src/redis-server" > usr.manifest
echo "/redis.conf: ${PWD}/redis.conf" >> usr.manifest
