#!/bin/sh

VERSION=5.6.21
BASEDIR=$PWD
BUILDDIR=$BASEDIR/build
ROOTDIR=$BASEDIR/install
SRCDIR=$BASEDIR/mysql-$VERSION

if [ ! -f mysql-$VERSION.tar.gz ]; then
    wget http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-$VERSION.tar.gz
fi
tar zxf mysql-$VERSION.tar.gz


mkdir -p $BUILDDIR
mkdir -p $ROOTDIR/etc

cd $SRCDIR
patch -p1 < ../osv.patch

cd $BUILDDIR
CFLAGS="-fPIC" CXXFLAGS="-fPIC" cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../mysql-$VERSION
make -j4
make install DESTDIR=$ROOTDIR

cd $ROOTDIR
egrep mysql /etc/services > etc/services
cp $BASEDIR/my.cnf etc/
cd usr

./scripts/mysql_install_db --force --basedir=./ --ldata=data
cat <<EOF | eval './bin/mysqld  --bootstrap --skip-grant-tables --basedir=./ --datadir=data --max_allowed_packet=8M --net_buffer_length=16K'
use mysql;
set table_type=myisam;
insert into user values('%', 'admin', password('osv'), 'Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','','','','',0,0,0);
EOF

cd $BUILDDIR/sql
$(cat CMakeFiles/mysqld.dir/link.txt) -shared
cd $BASEDIR

echo "
/etc/**: ${ROOTDIR}/etc/**
/usr/share/**: ${ROOTDIR}/usr/share/**
/usr/lib/**: ${ROOTDIR}/usr/lib/**
/usr/data/**: ${ROOTDIR}/usr/data/**
/usr/bin/mysqld: ${BUILDDIR}/sql/mysqld
" > usr.manifest
