#!/bin/sh
set -ex
mkdir upstream
cd upstream
JETTY_VERSION="9.2.11.v20150529"
wget "http://eclipse.org/downloads/download.php?file=/jetty/${JETTY_VERSION}/dist/jetty-distribution-${JETTY_VERSION}.tar.gz&r=1" -O jetty.tgz
tar zxvf jetty.tgz --strip-components=1
sed '/<!--$/d;/^ *-->$/d' demo-base/webapps/test.d/override-web.xml >/tmp/$$.xml
mv /tmp/$$.xml demo-base/webapps/test.d/override-web.xml
rm -f lib/setuid/libsetuid-osx.so
