#!/bin/sh
set -ex
mkdir upstream
cd upstream
wget "http://download.eclipse.org/jetty/stable-9/dist/jetty-distribution-9.2.6.v20141205.tar.gz" -O jetty.tgz
tar zxvf jetty.tgz --strip-components=1
sed '/<!--$/d;/^ *-->$/d' demo-base/webapps/test.d/override-web.xml >/tmp/$$.xml
mv /tmp/$$.xml demo-base/webapps/test.d/override-web.xml

